In [1]:
import platform
from pathlib import Path

import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
import pandas as pd

from vascular_superenhancement.utils.path_config import load_path_config, _PROJECT_ROOT

config_name = "local_mac" if platform.system() == "Darwin" else "all_patients"
pc = load_path_config(config_name)

PATIENT_DATA_DIR = pc.working_dir / "patient_data"
DS_FOLDER = "downsampled_full_fov_128x128x64_crop-17.5"

splits_df = pd.read_csv(_PROJECT_ROOT / "splits" / "splits_01-15-26.csv")
patients_df = splits_df[splits_df["split"].isin(["train", "validation", "test"])].copy()
patients_df = patients_df.sort_values(["split", "patient_id"]).reset_index(drop=True)

print(f"Non-skipped patients: {len(patients_df)}")

Found project root at: /home/ayeluru/vascular-superenhancement-4d-flow
Non-skipped patients: 209

In [2]:
VZ_FLOW_TAG = 5  # tag_0x0043_0x1030 == 5 is vz

results = []

for _, row in patients_df.iterrows():
    pid = row["patient_id"]
    split = row["split"]
    patient_dir = PATIENT_DATA_DIR / pid

    catalog_path = patient_dir / f"dicom_catalog_{pid}.csv"
    if not catalog_path.exists():
        print(f"SKIP {pid}: no DICOM catalog")
        results.append({"patient_id": pid, "split": split, "original_direction": "NO_CATALOG"})
        continue

    catalog = pd.read_csv(catalog_path)

    # Filter to 4D flow vz component
    vz_cat = catalog[catalog["tag_0x0043_0x1030"] == VZ_FLOW_TAG].copy()
    if len(vz_cat) == 0:
        print(f"SKIP {pid}: no vz component in catalog")
        results.append({"patient_id": pid, "split": split, "original_direction": "NO_VZ"})
        continue

    # Compute time_index and slice_index from instance numbers (original acquisition order)
    vz_cat["time_index"] = (vz_cat["instancenumber"] - 1) % vz_cat["cardiacnumberofimages"]
    vz_cat["slice_index"] = (vz_cat["instancenumber"] - 1) // vz_cat["cardiacnumberofimages"]

    # Extract z-coordinate from ImagePositionPatient
    vz_cat["ipp"] = vz_cat["imagepositionpatient"].apply(lambda x: np.array(eval(x)))
    vz_cat["z"] = vz_cat["ipp"].apply(lambda x: x[2])

    # Look at time_index 0, sorted by slice_index (original acquisition order)
    t0 = vz_cat[vz_cat["time_index"] == 0].sort_values("slice_index")
    z_values = t0["z"].values

    # Determine original direction
    z_diff = np.diff(z_values)
    n_increasing = np.sum(z_diff > 0)
    n_decreasing = np.sum(z_diff < 0)

    if n_increasing > n_decreasing:
        orig_dir = "I_to_S"  # z increases with slice_index
    elif n_decreasing > n_increasing:
        orig_dir = "S_to_I"  # z decreases with slice_index
    else:
        orig_dir = "AMBIGUOUS"

    # Compute slice normal from ImageOrientationPatient
    iop = vz_cat["imageorientation"].iloc[0]
    iop_arr = np.array(eval(iop))
    row_vec = iop_arr[:3]
    col_vec = iop_arr[3:]
    slice_normal = np.cross(row_vec, col_vec)
    dot_z = slice_normal[2]  # dot product with z-hat

    results.append({
        "patient_id": pid,
        "split": split,
        "original_direction": orig_dir,
        "n_slices": len(t0),
        "z_range": f"[{z_values.min():.1f}, {z_values.max():.1f}]",
        "z_first_slice": z_values[0],
        "z_last_slice": z_values[-1],
        "slice_normal_z": dot_z,
        "n_increasing": n_increasing,
        "n_decreasing": n_decreasing,
    })

results_df = pd.DataFrame(results)
print("\n=== Summary ===")
print(results_df["original_direction"].value_counts())
print(f"\nPatients originally S→I (needed flip): {(results_df['original_direction'] == 'S_to_I').sum()}")
print(f"Patients originally I→S (no flip):      {(results_df['original_direction'] == 'I_to_S').sum()}")

=== Summary ===
original_direction
I_to_S    117
S_to_I     92
Name: count, dtype: int64

Patients originally S→I (needed flip): 92
Patients originally I→S (no flip):      117

In [3]:
results_df

,patient_id,split,original_direction,n_slices,z_range,z_first_slice,z_last_slice,slice_normal_z,n_increasing,n_decreasing
0,Balboloop,test,I_to_S,140,"[-89.5, 160.7]",-89.5459,160.6540,0.999930,139,0
1,Biswifo,test,S_to_I,120,"[-211.9, -21.5]",-21.4812,-211.8810,0.999966,0,119
2,Bomatog,test,S_to_I,140,"[-124.9, 97.5]",97.4641,-124.9360,1.000040,0,139
3,Boochuto,test,S_to_I,120,"[-116.5, 73.9]",73.9028,-116.4970,0.999930,0,119
4,Boumorim,test,S_to_I,120,"[-87.7, 102.7]",102.6960,-87.7036,0.999966,0,119
...,...,...,...,...,...,...,...,...,...,...
204,Somenut,validation,I_to_S,152,"[6.8, 218.2]",6.8000,218.2000,0.999930,151,0
205,Suedrurnep,validation,I_to_S,140,"[-100.0, 122.5]",-99.9500,122.4500,0.999942,139,0
206,Swibihek,validation,I_to_S,120,"[144.3, 334.7]",144.3060,334.7070,1.000040,119,0
207,Ugitat,validation,S_to_I,140,"[-99.2, 95.4]",95.4250,-99.1751,1.000000,0,139
208,Upbapit,validation,S_to_I,152,"[11.5, 222.9]",222.8870,11.4878,0.999966,0,151

In [11]:
from scipy.stats import pearsonr

COMPONENTS = [
    ("4d_flow_vx", "4d_flow_vx_corr", "Vx"),
    ("4d_flow_vy", "4d_flow_vy_corr", "Vy"),
    ("4d_flow_vz", "4d_flow_vz_corr", "Vz"),
]

analysis_rows = []

for _, res in results_df.iterrows():
    pid = res["patient_id"]
    orig_dir = res["original_direction"]

    if orig_dir in ("NO_CATALOG", "NO_VZ"):
        continue

    ds_root = PATIENT_DATA_DIR / pid / "nifti" / DS_FOLDER
    row_data = {"patient_id": pid, "original_direction": orig_dir}

    for subfolder, corr_subfolder, label in COMPONENTS:
        uncorr_path = ds_root / subfolder / f"{subfolder}_{pid}_frame_00.nii.gz"
        corr_path = ds_root / corr_subfolder / f"{corr_subfolder}_{pid}_frame_00.nii.gz"

        if not uncorr_path.exists() or not corr_path.exists():
            row_data[f"{label}_r"] = np.nan
            row_data[f"{label}_sign"] = "MISSING"
            continue

        uncorr = nib.load(str(uncorr_path)).get_fdata(dtype=np.float32).ravel()
        corr = nib.load(str(corr_path)).get_fdata(dtype=np.float32).ravel()

        r, _ = pearsonr(uncorr, corr)
        r_neg, _ = pearsonr(uncorr, -corr)
        row_data[f"{label}_r"] = r
        row_data[f"{label}_r_neg"] = r_neg
        row_data[f"{label}_sign"] = "SAME" if r > 0 else "NEGATED"

    analysis_rows.append(row_data)
    print(f"{pid} done")

analysis_df = pd.DataFrame(analysis_rows)
print("\nDone.")

Balboloop done
Biswifo done
Bomatog done
Boochuto done
Boumorim done
Bovutou done
Cadotueg done
Detodu done
Diecudey done
Diepami done
Diequipi done
Dithigog done
Dublafer done
Dujomal done
Elagieg done
Golotag done
Grequafie done
Gueshifa done
Kuquelok done
Oduskueb done
Quetode done
Runusath done
Sepigoo done
Stonscuetof done
Suquepog done
Tercippun done
Tiepolem done
Tisupey done
Amifer done
Aruborn done
Asonlig done
Badiswu done
Bibathot done
Bogeebo done
Boudubat done
Burapo done
Butiswu done
Cadedag done
Cefaru done
Cemuquey done
Ceriba done
Ceyebum done
Coosimo done
Cornuefor done
Crutaswo done
Dalibul done
Dapafem done
Datokif done
Desoomi done
Diboscey done
Difresa done
Dinaspig done
Drusdinut done
Dudoblo done
Duquestank done
Dutungub done
Edengat done
Egumud done
Ekotey done
Emalem done
Epcedin done
Ernegur done
Erusar done
Eyostoy done
Fibrefob done
Fliesiemo done
Frahidiel done
Fudoquo done
Fuekeswa done
Fumtufoos done
Geedefou done
Gepeta done
Getahig done
Gidusi done
Gifranu done
Gikolu done
Glomahe done
Gobulou done
Grouzahue done
Gudulung done
Hapamiem done
Hekita done
Hetoprist done
Heynelap done
Hicuhe done
Hokuepu done
Hueregour done
Ifankab done
Irbrosgol done
Iribar done
Jacibkut done
Jagluque done
Janiru done
Japotorn done
Jemeegu done
Jenoomer done
Jiesieja done
Jiquiler done
Jousnisam done
Jufamich done
Junicri done
Kewasha done
Kihaquo done
Kistrolu done
Kofudun done
Kopejek done
Krujouque done
Kuchefre done
Kuebeeku done
Kuedristip done
Kufootag done
Kusksusuth done
Lamoga done
Liegibla done
Lielefak done
Liepoja done
Loflaka done
Lueduri done
Lumutot done
Lurakouk done
Mijobost done
Mugukood done
Naniduf done
Nobogik done
Nosite done
Noyetut done
Nufafe done
Obdufar done
Okarcug done
Omeflok done
Ostablip done
Osumud done
Pagoner done
Pamennar done
Pemiggig done
Phahofi done
Phidecro done
Phunitul done
Phuquicha done
Posbuten done
Preflefi done
Priseko done
Prubodusk done
Pubayue done
Pugishof done
Puquefre done
Quehokee done
Quidesue done
Quihoojol done
Quinudoul done
Quogosi done
Rayoloth done
Rotomouk done
Sahuhe done
Secochi done
Sejile done
Selebes done
Sevoopir done
Sipisa done
Sithiroo done
Slathalu done
Slesuegig done
Snonoque done
Socrowa done
Sopeyak done
Soyefaf done
Stragotom done
Strousuhe done
Sulokuf done
Tadilsog done
Talodut done
Tatufok done
Tecerouf done
Thameci done
Thisuga done
Tieriegi done
Tomamel done
Tosbeybrof done
Trecuquem done
Tubafu done
Tupotu done
Udmodas done
Udutek done
Urpofooy done
Ururtos done
Uzegbex done
Vokuba done
Wetufru done
Yobofre done
Apuefquor done
Befeto done
Fecoostra done
Fejoba done
Gemapoey done
Grefuci done
Gristropu done
Heruemey done
Ibdarnif done
Kacague done
Kadiforn done
Netstegup done
Nufotoy done
Quigliri done
Senaniel done
Somenut done
Suedrurnep done
Swibihek done
Ugitat done
Upbapit done

Done.

In [12]:
print("=" * 80)
print("SIGN CHECK: is corrected velocity negated relative to uncorrected?")
print("  SAME   = positive correlation → signs match (correct)")
print("  NEGATED = negative correlation → one is incorrectly negated")
print("=" * 80)

for label in ["Vx", "Vy", "Vz"]:
    col = f"{label}_sign"
    valid = analysis_df[analysis_df[col] != "MISSING"]
    negated_mask = valid[col] == "NEGATED"
    n_negated = negated_mask.sum()
    print(f"\n{label}: {n_negated}/{len(valid)} patients have NEGATED sign")
    if n_negated > 0:
        negated_patients = valid[negated_mask]
        by_dir = negated_patients.groupby("original_direction").size()
        print(f"  Breakdown by original direction: {dict(by_dir)}")

print("\n")
print("=" * 80)
print("CROSS-TAB: Original direction vs sign, per component")
print("=" * 80)
for label in ["Vx", "Vy", "Vz"]:
    col = f"{label}_sign"
    valid = analysis_df[analysis_df[col] != "MISSING"]
    print(f"\n--- {label} ---")
    print(pd.crosstab(valid["original_direction"], valid[col]))

print("\n")
print("=" * 80)
print("EXPECTED vs ACTUAL")
print("  I→S patients: vz should be negated once → corrected & uncorrected should match (SAME)")
print("  S→I patients: vz should be double-negated (=not negated) → if code only negated once,")
print("                corrected & uncorrected will be NEGATED (wrong sign)")
print("=" * 80)
vz_valid = analysis_df[analysis_df["Vz_sign"] != "MISSING"]
print(pd.crosstab(vz_valid["original_direction"], vz_valid["Vz_sign"], margins=True))

================================================================================
SIGN CHECK: is corrected velocity negated relative to uncorrected?
  SAME   = positive correlation → signs match (correct)
  NEGATED = negative correlation → one is incorrectly negated
================================================================================

Vx: 0/208 patients have NEGATED sign

Vy: 0/208 patients have NEGATED sign

Vz: 0/208 patients have NEGATED sign


================================================================================
CROSS-TAB: Original direction vs sign, per component
================================================================================

--- Vx ---
Vx_sign             SAME
original_direction
I_to_S               116
S_to_I                92

--- Vy ---
Vy_sign             SAME
original_direction
I_to_S               116
S_to_I                92

--- Vz ---
Vz_sign             SAME
original_direction
I_to_S               116
S_to_I                92


================================================================================
EXPECTED vs ACTUAL
  I→S patients: vz should be negated once → corrected & uncorrected should match (SAME)
  S→I patients: vz should be double-negated (=not negated) → if code only negated once,
                corrected & uncorrected will be NEGATED (wrong sign)
================================================================================
Vz_sign             SAME  All
original_direction
I_to_S               116  116
S_to_I                92   92
All                  208  208

In [13]:
display_cols = [
    "patient_id", "original_direction",
    "Vx_r", "Vx_r_neg", "Vx_sign",
    "Vy_r", "Vy_r_neg", "Vy_sign",
    "Vz_r", "Vz_r_neg", "Vz_sign",
]
with pd.option_context("display.max_rows", None, "display.float_format", "{:.4f}".format):
    display(analysis_df[display_cols].sort_values(["original_direction", "Vz_sign", "patient_id"]))

,patient_id,original_direction,Vx_r,Vx_r_neg,Vx_sign,Vy_r,Vy_r_neg,Vy_sign,Vz_r,Vz_r_neg,Vz_sign
42,Coosimo,I_to_S,NaN,NaN,MISSING,NaN,NaN,MISSING,NaN,NaN,MISSING
29,Aruborn,I_to_S,0.9174,-0.9174,SAME,0.9157,-0.9157,SAME,0.8449,-0.8449,SAME
30,Asonlig,I_to_S,0.9154,-0.9154,SAME,0.9059,-0.9059,SAME,0.9089,-0.9089,SAME
31,Badiswu,I_to_S,0.9579,-0.9579,SAME,0.9377,-0.9377,SAME,0.9636,-0.9636,SAME
0,Balboloop,I_to_S,0.9276,-0.9276,SAME,0.9066,-0.9066,SAME,0.9254,-0.9254,SAME
32,Bibathot,I_to_S,0.9859,-0.9859,SAME,0.9933,-0.9933,SAME,0.9891,-0.9891,SAME
34,Boudubat,I_to_S,0.9878,-0.9878,SAME,0.9943,-0.9943,SAME,0.9853,-0.9853,SAME
5,Bovutou,I_to_S,0.9948,-0.9948,SAME,0.9964,-0.9964,SAME,0.9942,-0.9942,SAME
36,Butiswu,I_to_S,0.9575,-0.9575,SAME,0.9811,-0.9811,SAME,0.9623,-0.9623,SAME
37,Cadedag,I_to_S,0.9490,-0.9490,SAME,0.9838,-0.9838,SAME,0.9394,-0.9394,SAME
38,Cefaru,I_to_S,0.9221,-0.9221,SAME,0.8679,-0.8679,SAME,0.9346,-0.9346,SAME
40,Ceriba,I_to_S,0.9745,-0.9745,SAME,0.9875,-0.9875,SAME,0.9693,-0.9693,SAME
43,Cornuefor,I_to_S,0.9954,-0.9954,SAME,0.9964,-0.9964,SAME,0.9897,-0.9897,SAME
44,Crutaswo,I_to_S,0.9869,-0.9869,SAME,0.9928,-0.9928,SAME,0.9874,-0.9874,SAME
45,Dalibul,I_to_S,0.9221,-0.9221,SAME,0.9380,-0.9380,SAME,0.9340,-0.9340,SAME
46,Dapafem,I_to_S,0.9848,-0.9848,SAME,0.9928,-0.9928,SAME,0.9878,-0.9878,SAME
47,Datokif,I_to_S,0.9979,-0.9979,SAME,0.9987,-0.9987,SAME,0.9982,-0.9982,SAME
48,Desoomi,I_to_S,0.9492,-0.9492,SAME,0.9816,-0.9816,SAME,0.9468,-0.9468,SAME
7,Detodu,I_to_S,0.8778,-0.8778,SAME,0.9156,-0.9156,SAME,0.8970,-0.8970,SAME
49,Diboscey,I_to_S,0.9724,-0.9724,SAME,0.9860,-0.9860,SAME,0.9769,-0.9769,SAME
8,Diecudey,I_to_S,0.9895,-0.9895,SAME,0.9888,-0.9888,SAME,0.9925,-0.9925,SAME
51,Dinaspig,I_to_S,0.9667,-0.9667,SAME,0.9805,-0.9805,SAME,0.9575,-0.9575,SAME
52,Drusdinut,I_to_S,0.9537,-0.9537,SAME,0.9607,-0.9607,SAME,0.9602,-0.9602,SAME
12,Dublafer,I_to_S,0.9785,-0.9785,SAME,0.9916,-0.9916,SAME,0.9857,-0.9857,SAME
54,Duquestank,I_to_S,0.9663,-0.9663,SAME,0.9822,-0.9822,SAME,0.8932,-0.8932,SAME
58,Ekotey,I_to_S,0.9401,-0.9401,SAME,0.9587,-0.9587,SAME,0.9418,-0.9418,SAME
14,Elagieg,I_to_S,0.9077,-0.9077,SAME,0.8956,-0.8956,SAME,0.8832,-0.8832,SAME
59,Emalem,I_to_S,0.8053,-0.8053,SAME,0.8557,-0.8557,SAME,0.8025,-0.8025,SAME
61,Ernegur,I_to_S,0.9512,-0.9512,SAME,0.9710,-0.9710,SAME,0.9527,-0.9527,SAME
191,Fecoostra,I_to_S,0.9432,-0.9432,SAME,0.9249,-0.9249,SAME,0.9344,-0.9344,SAME
192,Fejoba,I_to_S,0.9518,-0.9518,SAME,0.9793,-0.9793,SAME,0.9398,-0.9398,SAME
65,Fliesiemo,I_to_S,0.9085,-0.9085,SAME,0.8825,-0.8825,SAME,0.9027,-0.9027,SAME
68,Fuekeswa,I_to_S,0.8773,-0.8773,SAME,0.9279,-0.9279,SAME,0.8976,-0.8976,SAME
69,Fumtufoos,I_to_S,0.9668,-0.9668,SAME,0.9756,-0.9756,SAME,0.9627,-0.9627,SAME
70,Geedefou,I_to_S,0.9633,-0.9633,SAME,0.9882,-0.9882,SAME,0.9650,-0.9650,SAME
72,Getahig,I_to_S,0.9980,-0.9980,SAME,0.9986,-0.9986,SAME,0.9981,-0.9981,SAME
73,Gidusi,I_to_S,0.9294,-0.9294,SAME,0.9656,-0.9656,SAME,0.9477,-0.9477,SAME
75,Gikolu,I_to_S,0.9252,-0.9252,SAME,0.9327,-0.9327,SAME,0.9132,-0.9132,SAME
76,Glomahe,I_to_S,0.8982,-0.8982,SAME,0.9444,-0.9444,SAME,0.9075,-0.9075,SAME
77,Gobulou,I_to_S,0.9809,-0.9809,SAME,0.9851,-0.9851,SAME,0.9733,-0.9733,SAME
194,Grefuci,I_to_S,0.9085,-0.9085,SAME,0.9555,-0.9555,SAME,0.9297,-0.9297,SAME
16,Grequafie,I_to_S,0.9191,-0.9191,SAME,0.9324,-0.9324,SAME,0.8745,-0.8745,SAME
195,Gristropu,I_to_S,0.8512,-0.8512,SAME,0.8502,-0.8502,SAME,0.8776,-0.8776,SAME
79,Gudulung,I_to_S,0.9668,-0.9668,SAME,0.9819,-0.9819,SAME,0.9720,-0.9720,SAME
17,Gueshifa,I_to_S,0.9064,-0.9064,SAME,0.9475,-0.9475,SAME,0.9047,-0.9047,SAME
80,Hapamiem,I_to_S,0.9631,-0.9631,SAME,0.9839,-0.9839,SAME,0.9494,-0.9494,SAME
81,Hekita,I_to_S,0.8974,-0.8974,SAME,0.9409,-0.9409,SAME,0.8936,-0.8936,SAME
82,Hetoprist,I_to_S,0.8708,-0.8708,SAME,0.8056,-0.8056,SAME,0.9000,-0.9000,SAME
85,Hokuepu,I_to_S,0.9224,-0.9224,SAME,0.9585,-0.9585,SAME,0.9248,-0.9248,SAME
86,Hueregour,I_to_S,0.9885,-0.9885,SAME,0.9906,-0.9906,SAME,0.9834,-0.9834,SAME
87,Ifankab,I_to_S,0.9977,-0.9977,SAME,0.9990,-0.9990,SAME,0.9980,-0.9980,SAME
90,Jacibkut,I_to_S,0.9540,-0.9540,SAME,0.9829,-0.9829,SAME,0.9573,-0.9573,SAME
91,Jagluque,I_to_S,0.9422,-0.9422,SAME,0.9751,-0.9751,SAME,0.9471,-0.9471,SAME
92,Janiru,I_to_S,0.8946,-0.8946,SAME,0.8908,-0.8908,SAME,0.9291,-0.9291,SAME
93,Japotorn,I_to_S,0.9796,-0.9796,SAME,0.9793,-0.9793,SAME,0.9749,-0.9749,SAME
94,Jemeegu,I_to_S,0.9622,-0.9622,SAME,0.9876,-0.9876,SAME,0.9691,-0.9691,SAME
95,Jenoomer,I_to_S,0.8475,-0.8475,SAME,0.8864,-0.8864,SAME,0.8813,-0.8813,SAME
98,Jousnisam,I_to_S,0.9595,-0.9595,SAME,0.9806,-0.9806,SAME,0.9459,-0.9459,SAME
99,Jufamich,I_to_S,0.8916,-0.8916,SAME,0.9221,-0.9221,SAME,0.9066,-0.9066,SAME
198,Kacague,I_to_S,0.9704,-0.9704,SAME,0.9668,-0.9668,SAME,0.9590,-0.9590,SAME
103,Kistrolu,I_to_S,0.9602,-0.9602,SAME,0.9018,-0.9018,SAME,0.9488,-0.9488,SAME
104,Kofudun,I_to_S,0.9663,-0.9663,SAME,0.9795,-0.9795,SAME,0.9624,-0.9624,SAME
105,Kopejek,I_to_S,0.9402,-0.9402,SAME,0.9733,-0.9733,SAME,0.9496,-0.9496,SAME
106,Krujouque,I_to_S,0.9699,-0.9699,SAME,0.9909,-0.9909,SAME,0.9683,-0.9683,SAME
108,Kuebeeku,I_to_S,0.9609,-0.9609,SAME,0.9803,-0.9803,SAME,0.9703,-0.9703,SAME
109,Kuedristip,I_to_S,0.9615,-0.9615,SAME,0.9429,-0.9429,SAME,0.9370,-0.9370,SAME
113,Liegibla,I_to_S,0.9512,-0.9512,SAME,0.9774,-0.9774,SAME,0.9589,-0.9589,SAME
115,Liepoja,I_to_S,0.9846,-0.9846,SAME,0.9938,-0.9938,SAME,0.9834,-0.9834,SAME
116,Loflaka,I_to_S,0.9691,-0.9691,SAME,0.9702,-0.9702,SAME,0.9486,-0.9486,SAME
117,Lueduri,I_to_S,0.9000,-0.9000,SAME,0.9484,-0.9484,SAME,0.9111,-0.9111,SAME
118,Lumutot,I_to_S,0.9562,-0.9562,SAME,0.9763,-0.9763,SAME,0.9587,-0.9587,SAME
119,Lurakouk,I_to_S,0.9452,-0.9452,SAME,0.9566,-0.9566,SAME,0.9430,-0.9430,SAME
121,Mugukood,I_to_S,0.9736,-0.9736,SAME,0.9901,-0.9901,SAME,0.9809,-0.9809,SAME
124,Nosite,I_to_S,0.9703,-0.9703,SAME,0.9886,-0.9886,SAME,0.9464,-0.9464,SAME
125,Noyetut,I_to_S,0.9653,-0.9653,SAME,0.9830,-0.9830,SAME,0.9687,-0.9687,SAME
126,Nufafe,I_to_S,0.9381,-0.9381,SAME,0.9633,-0.9633,SAME,0.9529,-0.9529,SAME
128,Okarcug,I_to_S,0.9851,-0.9851,SAME,0.9905,-0.9905,SAME,0.9824,-0.9824,SAME
129,Omeflok,I_to_S,0.9118,-0.9118,SAME,0.9446,-0.9446,SAME,0.9301,-0.9301,SAME
130,Ostablip,I_to_S,0.9769,-0.9769,SAME,0.9910,-0.9910,SAME,0.9785,-0.9785,SAME
131,Osumud,I_to_S,0.9748,-0.9748,SAME,0.9870,-0.9870,SAME,0.9739,-0.9739,SAME
132,Pagoner,I_to_S,0.9090,-0.9090,SAME,0.8902,-0.8902,SAME,0.9206,-0.9206,SAME
133,Pamennar,I_to_S,0.9784,-0.9784,SAME,0.9897,-0.9897,SAME,0.9799,-0.9799,SAME
134,Pemiggig,I_to_S,0.9642,-0.9642,SAME,0.9847,-0.9847,SAME,0.9697,-0.9697,SAME
135,Phahofi,I_to_S,0.9877,-0.9877,SAME,0.9875,-0.9875,SAME,0.9865,-0.9865,SAME
136,Phidecro,I_to_S,0.9953,-0.9953,SAME,0.9805,-0.9805,SAME,0.9917,-0.9917,SAME
138,Phuquicha,I_to_S,0.9182,-0.9182,SAME,0.9545,-0.9545,SAME,0.9406,-0.9406,SAME
141,Priseko,I_to_S,0.9440,-0.9440,SAME,0.9455,-0.9455,SAME,0.9519,-0.9519,SAME
142,Prubodusk,I_to_S,0.9818,-0.9818,SAME,0.9673,-0.9673,SAME,0.9684,-0.9684,SAME
143,Pubayue,I_to_S,0.9796,-0.9796,SAME,0.9846,-0.9846,SAME,0.9779,-0.9779,SAME
147,Quidesue,I_to_S,0.8457,-0.8457,SAME,0.8892,-0.8892,SAME,0.8291,-0.8291,SAME
202,Quigliri,I_to_S,0.9228,-0.9228,SAME,0.9595,-0.9595,SAME,0.9095,-0.9095,SAME
149,Quinudoul,I_to_S,0.9645,-0.9645,SAME,0.9773,-0.9773,SAME,0.9651,-0.9651,SAME
150,Quogosi,I_to_S,0.9829,-0.9829,SAME,0.9884,-0.9884,SAME,0.9819,-0.9819,SAME
152,Rotomouk,I_to_S,0.8738,-0.8738,SAME,0.8515,-0.8515,SAME,0.8893,-0.8893,SAME
155,Sejile,I_to_S,0.9559,-0.9559,SAME,0.9763,-0.9763,SAME,0.9637,-0.9637,SAME
156,Selebes,I_to_S,0.9493,-0.9493,SAME,0.9506,-0.9506,SAME,0.9409,-0.9409,SAME
203,Senaniel,I_to_S,0.9822,-0.9822,SAME,0.9955,-0.9955,SAME,0.9850,-0.9850,SAME
157,Sevoopir,I_to_S,0.9429,-0.9429,SAME,0.8588,-0.8588,SAME,0.9468,-0.9468,SAME
160,Slathalu,I_to_S,0.9829,-0.9829,SAME,0.9936,-0.9936,SAME,0.9814,-0.9814,SAME
161,Slesuegig,I_to_S,0.9913,-0.9913,SAME,0.9967,-0.9967,SAME,0.9887,-0.9887,SAME
204,Somenut,I_to_S,0.9235,-0.9235,SAME,0.9082,-0.9082,SAME,0.9311,-0.9311,SAME
166,Stragotom,I_to_S,0.9430,-0.9430,SAME,0.9562,-0.9562,SAME,0.9561,-0.9561,SAME
205,Suedrurnep,I_to_S,0.9399,-0.9399,SAME,0.9513,-0.9513,SAME,0.9430,-0.9430,SAME
168,Sulokuf,I_to_S,0.9338,-0.9338,SAME,0.9717,-0.9717,SAME,0.9218,-0.9218,SAME
24,Suquepog,I_to_S,0.9329,-0.9329,SAME,0.9149,-0.9149,SAME,0.9259,-0.9259,SAME
206,Swibihek,I_to_S,0.6513,-0.6513,SAME,0.7889,-0.7889,SAME,0.8631,-0.8631,SAME
169,Tadilsog,I_to_S,0.9834,-0.9834,SAME,0.9884,-0.9884,SAME,0.9812,-0.9812,SAME
171,Tatufok,I_to_S,0.9885,-0.9885,SAME,0.9958,-0.9958,SAME,0.9918,-0.9918,SAME
173,Thameci,I_to_S,0.9702,-0.9702,SAME,0.9731,-0.9731,SAME,0.9645,-0.9645,SAME
174,Thisuga,I_to_S,0.9929,-0.9929,SAME,0.9968,-0.9968,SAME,0.9887,-0.9887,SAME
176,Tomamel,I_to_S,0.9653,-0.9653,SAME,0.9565,-0.9565,SAME,0.9098,-0.9098,SAME
177,Tosbeybrof,I_to_S,0.9303,-0.9303,SAME,0.8550,-0.8550,SAME,0.9227,-0.9227,SAME
178,Trecuquem,I_to_S,0.9339,-0.9339,SAME,0.9492,-0.9492,SAME,0.9190,-0.9190,SAME
179,Tubafu,I_to_S,0.9914,-0.9914,SAME,0.9970,-0.9970,SAME,0.9907,-0.9907,SAME
181,Udmodas,I_to_S,0.8936,-0.8936,SAME,0.9376,-0.9376,SAME,0.9167,-0.9167,SAME
185,Uzegbex,I_to_S,0.9484,-0.9484,SAME,0.9419,-0.9419,SAME,0.9319,-0.9319,SAME
188,Yobofre,I_to_S,0.9580,-0.9580,SAME,0.9041,-0.9041,SAME,0.9495,-0.9495,SAME
28,Amifer,S_to_I,0.8912,-0.8912,SAME,0.9047,-0.9047,SAME,0.8821,-0.8821,SAME
189,Apuefquor,S_to_I,0.9637,-0.9637,SAME,0.9628,-0.9628,SAME,0.9629,-0.9629,SAME
190,Befeto,S_to_I,0.9078,-0.9078,SAME,0.8289,-0.8289,SAME,0.9075,-0.9075,SAME
1,Biswifo,S_to_I,0.9038,-0.9038,SAME,0.9103,-0.9103,SAME,0.9205,-0.9205,SAME
33,Bogeebo,S_to_I,0.9890,-0.9890,SAME,0.9908,-0.9908,SAME,0.9817,-0.9817,SAME
2,Bomatog,S_to_I,0.9510,-0.9510,SAME,0.9489,-0.9489,SAME,0.9353,-0.9353,SAME
3,Boochuto,S_to_I,0.9477,-0.9477,SAME,0.9655,-0.9655,SAME,0.9103,-0.9103,SAME
4,Boumorim,S_to_I,0.9331,-0.9331,SAME,0.9190,-0.9190,SAME,0.8480,-0.8480,SAME
35,Burapo,S_to_I,0.9848,-0.9848,SAME,0.9799,-0.9799,SAME,0.9846,-0.9846,SAME
6,Cadotueg,S_to_I,0.8894,-0.8894,SAME,0.9528,-0.9528,SAME,0.8947,-0.8947,SAME
39,Cemuquey,S_to_I,0.9451,-0.9451,SAME,0.9361,-0.9361,SAME,0.9481,-0.9481,SAME
41,Ceyebum,S_to_I,0.9037,-0.9037,SAME,0.9079,-0.9079,SAME,0.8853,-0.8853,SAME
9,Diepami,S_to_I,0.9726,-0.9726,SAME,0.9639,-0.9639,SAME,0.9795,-0.9795,SAME
10,Diequipi,S_to_I,0.9261,-0.9261,SAME,0.9240,-0.9240,SAME,0.9168,-0.9168,SAME
50,Difresa,S_to_I,0.9526,-0.9526,SAME,0.9366,-0.9366,SAME,0.9512,-0.9512,SAME
11,Dithigog,S_to_I,0.8662,-0.8662,SAME,0.9258,-0.9258,SAME,0.8930,-0.8930,SAME
53,Dudoblo,S_to_I,0.8629,-0.8629,SAME,0.8678,-0.8678,SAME,0.8582,-0.8582,SAME
13,Dujomal,S_to_I,0.9637,-0.9637,SAME,0.9702,-0.9702,SAME,0.9596,-0.9596,SAME
55,Dutungub,S_to_I,0.9437,-0.9437,SAME,0.9078,-0.9078,SAME,0.9272,-0.9272,SAME
56,Edengat,S_to_I,0.9225,-0.9225,SAME,0.9069,-0.9069,SAME,0.9220,-0.9220,SAME
57,Egumud,S_to_I,0.9541,-0.9541,SAME,0.9659,-0.9659,SAME,0.9367,-0.9367,SAME
60,Epcedin,S_to_I,0.9723,-0.9723,SAME,0.9671,-0.9671,SAME,0.9752,-0.9752,SAME
62,Erusar,S_to_I,0.9514,-0.9514,SAME,0.9520,-0.9520,SAME,0.9598,-0.9598,SAME
63,Eyostoy,S_to_I,0.9831,-0.9831,SAME,0.9877,-0.9877,SAME,0.9824,-0.9824,SAME
64,Fibrefob,S_to_I,0.9539,-0.9539,SAME,0.9631,-0.9631,SAME,0.9559,-0.9559,SAME
66,Frahidiel,S_to_I,0.9208,-0.9208,SAME,0.9316,-0.9316,SAME,0.9289,-0.9289,SAME
67,Fudoquo,S_to_I,0.9051,-0.9051,SAME,0.9017,-0.9017,SAME,0.8933,-0.8933,SAME
193,Gemapoey,S_to_I,0.9282,-0.9282,SAME,0.9419,-0.9419,SAME,0.9260,-0.9260,SAME
71,Gepeta,S_to_I,0.8679,-0.8679,SAME,0.8897,-0.8897,SAME,0.9136,-0.9136,SAME
74,Gifranu,S_to_I,0.9720,-0.9720,SAME,0.9181,-0.9181,SAME,0.9587,-0.9587,SAME
15,Golotag,S_to_I,0.8859,-0.8859,SAME,0.8856,-0.8856,SAME,0.8872,-0.8872,SAME
78,Grouzahue,S_to_I,0.9559,-0.9559,SAME,0.9738,-0.9738,SAME,0.9598,-0.9598,SAME
196,Heruemey,S_to_I,0.9767,-0.9767,SAME,0.9813,-0.9813,SAME,0.9529,-0.9529,SAME
83,Heynelap,S_to_I,0.9327,-0.9327,SAME,0.9491,-0.9491,SAME,0.9242,-0.9242,SAME
84,Hicuhe,S_to_I,0.9265,-0.9265,SAME,0.9329,-0.9329,SAME,0.9179,-0.9179,SAME
197,Ibdarnif,S_to_I,0.9263,-0.9263,SAME,0.9126,-0.9126,SAME,0.9254,-0.9254,SAME
88,Irbrosgol,S_to_I,0.9539,-0.9539,SAME,0.9335,-0.9335,SAME,0.9571,-0.9571,SAME
89,Iribar,S_to_I,0.9454,-0.9454,SAME,0.9582,-0.9582,SAME,0.9464,-0.9464,SAME
96,Jiesieja,S_to_I,0.9289,-0.9289,SAME,0.9463,-0.9463,SAME,0.8792,-0.8792,SAME
97,Jiquiler,S_to_I,0.8607,-0.8607,SAME,0.8817,-0.8817,SAME,0.8883,-0.8883,SAME
100,Junicri,S_to_I,0.9324,-0.9324,SAME,0.8885,-0.8885,SAME,0.8844,-0.8844,SAME
199,Kadiforn,S_to_I,0.9310,-0.9310,SAME,0.9166,-0.9166,SAME,0.9205,-0.9205,SAME
101,Kewasha,S_to_I,0.9510,-0.9510,SAME,0.9725,-0.9725,SAME,0.9487,-0.9487,SAME
102,Kihaquo,S_to_I,0.9298,-0.9298,SAME,0.8966,-0.8966,SAME,0.8864,-0.8864,SAME
107,Kuchefre,S_to_I,0.8696,-0.8696,SAME,0.8436,-0.8436,SAME,0.8601,-0.8601,SAME
110,Kufootag,S_to_I,0.8202,-0.8202,SAME,0.8948,-0.8948,SAME,0.8897,-0.8897,SAME
18,Kuquelok,S_to_I,0.9548,-0.9548,SAME,0.9308,-0.9308,SAME,0.9026,-0.9026,SAME
111,Kusksusuth,S_to_I,0.9388,-0.9388,SAME,0.9197,-0.9197,SAME,0.9373,-0.9373,SAME
112,Lamoga,S_to_I,0.9127,-0.9127,SAME,0.9063,-0.9063,SAME,0.9024,-0.9024,SAME
114,Lielefak,S_to_I,0.9434,-0.9434,SAME,0.9234,-0.9234,SAME,0.9496,-0.9496,SAME
120,Mijobost,S_to_I,0.9598,-0.9598,SAME,0.9372,-0.9372,SAME,0.9665,-0.9665,SAME
122,Naniduf,S_to_I,0.9916,-0.9916,SAME,0.9897,-0.9897,SAME,0.9841,-0.9841,SAME
200,Netstegup,S_to_I,0.9538,-0.9538,SAME,0.9301,-0.9301,SAME,0.9539,-0.9539,SAME
123,Nobogik,S_to_I,0.9207,-0.9207,SAME,0.9074,-0.9074,SAME,0.9305,-0.9305,SAME
201,Nufotoy,S_to_I,0.9746,-0.9746,SAME,0.9591,-0.9591,SAME,0.9801,-0.9801,SAME
127,Obdufar,S_to_I,0.8942,-0.8942,SAME,0.8846,-0.8846,SAME,0.9034,-0.9034,SAME
19,Oduskueb,S_to_I,0.9127,-0.9127,SAME,0.9430,-0.9430,SAME,0.9409,-0.9409,SAME
137,Phunitul,S_to_I,0.9763,-0.9763,SAME,0.9426,-0.9426,SAME,0.9874,-0.9874,SAME
139,Posbuten,S_to_I,0.8736,-0.8736,SAME,0.8924,-0.8924,SAME,0.8630,-0.8630,SAME
140,Preflefi,S_to_I,1.0000,-1.0000,SAME,1.0000,-1.0000,SAME,1.0000,-1.0000,SAME
144,Pugishof,S_to_I,0.9262,-0.9262,SAME,0.9613,-0.9613,SAME,0.9302,-0.9302,SAME
145,Puquefre,S_to_I,0.9286,-0.9286,SAME,0.9226,-0.9226,SAME,0.9328,-0.9328,SAME
146,Quehokee,S_to_I,0.9510,-0.9510,SAME,0.9616,-0.9616,SAME,0.9521,-0.9521,SAME
20,Quetode,S_to_I,0.8729,-0.8729,SAME,0.8284,-0.8284,SAME,0.8592,-0.8592,SAME
148,Quihoojol,S_to_I,0.9635,-0.9635,SAME,0.9126,-0.9126,SAME,0.9668,-0.9668,SAME
151,Rayoloth,S_to_I,0.8455,-0.8455,SAME,0.8963,-0.8963,SAME,0.8647,-0.8647,SAME
21,Runusath,S_to_I,0.8147,-0.8147,SAME,0.8541,-0.8541,SAME,0.8755,-0.8755,SAME
153,Sahuhe,S_to_I,0.9321,-0.9321,SAME,0.8871,-0.8871,SAME,0.9369,-0.9369,SAME
154,Secochi,S_to_I,0.8621,-0.8621,SAME,0.8798,-0.8798,SAME,0.8270,-0.8270,SAME
22,Sepigoo,S_to_I,0.8914,-0.8914,SAME,0.9257,-0.9257,SAME,0.8676,-0.8676,SAME
158,Sipisa,S_to_I,0.9224,-0.9224,SAME,0.9055,-0.9055,SAME,0.9115,-0.9115,SAME
159,Sithiroo,S_to_I,0.9603,-0.9603,SAME,0.9515,-0.9515,SAME,0.9654,-0.9654,SAME
162,Snonoque,S_to_I,0.9461,-0.9461,SAME,0.9492,-0.9492,SAME,0.9448,-0.9448,SAME
163,Socrowa,S_to_I,0.9308,-0.9308,SAME,0.9288,-0.9288,SAME,0.9041,-0.9041,SAME
164,Sopeyak,S_to_I,0.8452,-0.8452,SAME,0.8744,-0.8744,SAME,0.8349,-0.8349,SAME
165,Soyefaf,S_to_I,0.9746,-0.9746,SAME,0.9794,-0.9794,SAME,0.9687,-0.9687,SAME
23,Stonscuetof,S_to_I,0.9416,-0.9416,SAME,0.9131,-0.9131,SAME,0.9494,-0.9494,SAME
167,Strousuhe,S_to_I,0.9570,-0.9570,SAME,0.9693,-0.9693,SAME,0.9441,-0.9441,SAME
170,Talodut,S_to_I,0.9056,-0.9056,SAME,0.9140,-0.9140,SAME,0.9132,-0.9132,SAME
172,Tecerouf,S_to_I,0.8739,-0.8739,SAME,0.9210,-0.9210,SAME,0.9110,-0.9110,SAME
25,Tercippun,S_to_I,0.9851,-0.9851,SAME,0.9810,-0.9810,SAME,0.9855,-0.9855,SAME
26,Tiepolem,S_to_I,0.9540,-0.9540,SAME,0.9688,-0.9688,SAME,0.9592,-0.9592,SAME
175,Tieriegi,S_to_I,0.9337,-0.9337,SAME,0.9168,-0.9168,SAME,0.9225,-0.9225,SAME
27,Tisupey,S_to_I,0.8870,-0.8870,SAME,0.9419,-0.9419,SAME,0.9311,-0.9311,SAME
180,Tupotu,S_to_I,0.9036,-0.9036,SAME,0.9204,-0.9204,SAME,0.9122,-0.9122,SAME
182,Udutek,S_to_I,0.8553,-0.8553,SAME,0.8924,-0.8924,SAME,0.8849,-0.8849,SAME
207,Ugitat,S_to_I,0.9477,-0.9477,SAME,0.9240,-0.9240,SAME,0.9445,-0.9445,SAME
208,Upbapit,S_to_I,0.9323,-0.9323,SAME,0.9124,-0.9124,SAME,0.9504,-0.9504,SAME
183,Urpofooy,S_to_I,0.9785,-0.9785,SAME,0.9501,-0.9501,SAME,0.9856,-0.9856,SAME
184,Ururtos,S_to_I,0.9457,-0.9457,SAME,0.9530,-0.9530,SAME,0.9464,-0.9464,SAME
186,Vokuba,S_to_I,0.9304,-0.9304,SAME,0.9182,-0.9182,SAME,0.9168,-0.9168,SAME
187,Wetufru,S_to_I,0.9241,-0.9241,SAME,0.9028,-0.9028,SAME,0.8862,-0.8862,SAME

In [4]:
OUTPUT_DIR = Path("velocity_direction_check_images")
OUTPUT_DIR.mkdir(exist_ok=True)


def load_vol(path: Path) -> np.ndarray:
    return nib.load(str(path)).get_fdata(dtype=np.float32)


for i, (_, res) in enumerate(results_df.iterrows()):
    pid = res["patient_id"]
    orig_dir = res["original_direction"]

    if orig_dir in ("NO_CATALOG", "NO_VZ"):
        continue

    ds_root = PATIENT_DATA_DIR / pid / "nifti" / DS_FOLDER
    vz_path = ds_root / "4d_flow_vz" / f"4d_flow_vz_{pid}_frame_00.nii.gz"
    vz_corr_path = ds_root / "4d_flow_vz_corr" / f"4d_flow_vz_corr_{pid}_frame_00.nii.gz"
    diff_vz_path = ds_root / "4d_flow_diff_vz" / f"4d_flow_diff_vz_{pid}_frame_00.nii.gz"

    if not vz_path.exists() or not vz_corr_path.exists():
        print(f"SKIP {pid}: missing vz or vz_corr")
        continue

    vz = load_vol(vz_path)
    vz_corr = load_vol(vz_corr_path)
    has_diff = diff_vz_path.exists()
    diff_vz = load_vol(diff_vz_path) if has_diff else vz_corr - vz

    n_slices = vz.shape[2]
    mid_z = n_slices // 2
    slices_to_show = [0, n_slices // 4, mid_z, 3 * n_slices // 4, n_slices - 1]

    n_cols = len(slices_to_show)
    fig, axes = plt.subplots(3, n_cols, figsize=(3.5 * n_cols, 9))

    needed_flip = "YES" if orig_dir == "S_to_I" else "NO"
    fig.suptitle(
        f"{pid}  |  Original: {orig_dir}  |  Needed flip: {needed_flip}  |  "
        f"slice_normal_z: {res.get('slice_normal_z', 'N/A'):.3f}",
        fontsize=12, fontweight="bold", y=1.02,
    )

    row_labels = ["Uncorrected Vz", "Corrected Vz", "Diff (corr - uncorr)"]

    for c, si in enumerate(slices_to_show):
        vz_slice = vz[:, :, si].T
        vz_corr_slice = vz_corr[:, :, si].T
        diff_slice = diff_vz[:, :, si].T

        # Symmetric color range for each
        vmax_vz = np.percentile(np.abs(vz), 99)
        vmax_corr = np.percentile(np.abs(vz_corr), 99)
        vmax_diff = np.percentile(np.abs(diff_vz), 99) if np.any(diff_vz != 0) else 1.0

        for r, (slc, vmax) in enumerate([
            (vz_slice, vmax_vz),
            (vz_corr_slice, vmax_corr),
            (diff_slice, vmax_diff),
        ]):
            ax = axes[r, c]
            ax.imshow(slc, origin="lower", cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="equal")
            ax.set_xticks([])
            ax.set_yticks([])
            if r == 0:
                ax.set_title(f"z={si}", fontsize=10)
            if c == 0:
                ax.set_ylabel(row_labels[r], fontsize=10)

    plt.tight_layout()
    fig.savefig(OUTPUT_DIR / f"{orig_dir}_{pid}.png", dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"[{i+1}/{len(results_df)}] {pid} ({orig_dir})")

print(f"\nDone. Images saved to {OUTPUT_DIR.resolve()}")

[1/209] Balboloop (I_to_S)
[2/209] Biswifo (S_to_I)
[3/209] Bomatog (S_to_I)
[4/209] Boochuto (S_to_I)
[5/209] Boumorim (S_to_I)
[6/209] Bovutou (I_to_S)
[7/209] Cadotueg (S_to_I)
[8/209] Detodu (I_to_S)
[9/209] Diecudey (I_to_S)
[10/209] Diepami (S_to_I)
[11/209] Diequipi (S_to_I)
[12/209] Dithigog (S_to_I)
[13/209] Dublafer (I_to_S)
[14/209] Dujomal (S_to_I)
[15/209] Elagieg (I_to_S)
[16/209] Golotag (S_to_I)
[17/209] Grequafie (I_to_S)
[18/209] Gueshifa (I_to_S)
[19/209] Kuquelok (S_to_I)
[20/209] Oduskueb (S_to_I)
[21/209] Quetode (S_to_I)
[22/209] Runusath (S_to_I)
[23/209] Sepigoo (S_to_I)
[24/209] Stonscuetof (S_to_I)
[25/209] Suquepog (I_to_S)
[26/209] Tercippun (S_to_I)
[27/209] Tiepolem (S_to_I)
[28/209] Tisupey (S_to_I)
[29/209] Amifer (S_to_I)
[30/209] Aruborn (I_to_S)
[31/209] Asonlig (I_to_S)
[32/209] Badiswu (I_to_S)
[33/209] Bibathot (I_to_S)
[34/209] Bogeebo (S_to_I)
[35/209] Boudubat (I_to_S)
[36/209] Burapo (S_to_I)
[37/209] Butiswu (I_to_S)
[38/209] Cadedag (I_to_S)
[39/209] Cefaru (I_to_S)
[40/209] Cemuquey (S_to_I)
[41/209] Ceriba (I_to_S)
[42/209] Ceyebum (S_to_I)
SKIP Coosimo: missing vz or vz_corr
[44/209] Cornuefor (I_to_S)
[45/209] Crutaswo (I_to_S)
[46/209] Dalibul (I_to_S)
[47/209] Dapafem (I_to_S)
[48/209] Datokif (I_to_S)
[49/209] Desoomi (I_to_S)
[50/209] Diboscey (I_to_S)
[51/209] Difresa (S_to_I)
[52/209] Dinaspig (I_to_S)
[53/209] Drusdinut (I_to_S)
[54/209] Dudoblo (S_to_I)
[55/209] Duquestank (I_to_S)
[56/209] Dutungub (S_to_I)
[57/209] Edengat (S_to_I)
[58/209] Egumud (S_to_I)
[59/209] Ekotey (I_to_S)
[60/209] Emalem (I_to_S)
[61/209] Epcedin (S_to_I)
[62/209] Ernegur (I_to_S)
[63/209] Erusar (S_to_I)
[64/209] Eyostoy (S_to_I)
[65/209] Fibrefob (S_to_I)
[66/209] Fliesiemo (I_to_S)
[67/209] Frahidiel (S_to_I)
[68/209] Fudoquo (S_to_I)
[69/209] Fuekeswa (I_to_S)
[70/209] Fumtufoos (I_to_S)
[71/209] Geedefou (I_to_S)
[72/209] Gepeta (S_to_I)
[73/209] Getahig (I_to_S)
[74/209] Gidusi (I_to_S)
[75/209] Gifranu (S_to_I)
[76/209] Gikolu (I_to_S)
[77/209] Glomahe (I_to_S)
[78/209] Gobulou (I_to_S)
[79/209] Grouzahue (S_to_I)
[80/209] Gudulung (I_to_S)
[81/209] Hapamiem (I_to_S)
[82/209] Hekita (I_to_S)
[83/209] Hetoprist (I_to_S)
[84/209] Heynelap (S_to_I)
[85/209] Hicuhe (S_to_I)
[86/209] Hokuepu (I_to_S)
[87/209] Hueregour (I_to_S)
[88/209] Ifankab (I_to_S)
[89/209] Irbrosgol (S_to_I)
[90/209] Iribar (S_to_I)
[91/209] Jacibkut (I_to_S)
[92/209] Jagluque (I_to_S)
[93/209] Janiru (I_to_S)
[94/209] Japotorn (I_to_S)
[95/209] Jemeegu (I_to_S)
[96/209] Jenoomer (I_to_S)
[97/209] Jiesieja (S_to_I)
[98/209] Jiquiler (S_to_I)
[99/209] Jousnisam (I_to_S)
[100/209] Jufamich (I_to_S)
[101/209] Junicri (S_to_I)
[102/209] Kewasha (S_to_I)
[103/209] Kihaquo (S_to_I)
[104/209] Kistrolu (I_to_S)
[105/209] Kofudun (I_to_S)
[106/209] Kopejek (I_to_S)
[107/209] Krujouque (I_to_S)
[108/209] Kuchefre (S_to_I)
[109/209] Kuebeeku (I_to_S)
[110/209] Kuedristip (I_to_S)
[111/209] Kufootag (S_to_I)
[112/209] Kusksusuth (S_to_I)
[113/209] Lamoga (S_to_I)
[114/209] Liegibla (I_to_S)
[115/209] Lielefak (S_to_I)
[116/209] Liepoja (I_to_S)
[117/209] Loflaka (I_to_S)
[118/209] Lueduri (I_to_S)
[119/209] Lumutot (I_to_S)
[120/209] Lurakouk (I_to_S)
[121/209] Mijobost (S_to_I)
[122/209] Mugukood (I_to_S)
[123/209] Naniduf (S_to_I)
[124/209] Nobogik (S_to_I)
[125/209] Nosite (I_to_S)
[126/209] Noyetut (I_to_S)
[127/209] Nufafe (I_to_S)
[128/209] Obdufar (S_to_I)
[129/209] Okarcug (I_to_S)
[130/209] Omeflok (I_to_S)
[131/209] Ostablip (I_to_S)
[132/209] Osumud (I_to_S)
[133/209] Pagoner (I_to_S)
[134/209] Pamennar (I_to_S)
[135/209] Pemiggig (I_to_S)
[136/209] Phahofi (I_to_S)
[137/209] Phidecro (I_to_S)
[138/209] Phunitul (S_to_I)
[139/209] Phuquicha (I_to_S)
[140/209] Posbuten (S_to_I)
[141/209] Preflefi (S_to_I)
[142/209] Priseko (I_to_S)
[143/209] Prubodusk (I_to_S)
[144/209] Pubayue (I_to_S)
[145/209] Pugishof (S_to_I)
[146/209] Puquefre (S_to_I)
[147/209] Quehokee (S_to_I)
[148/209] Quidesue (I_to_S)
[149/209] Quihoojol (S_to_I)
[150/209] Quinudoul (I_to_S)
[151/209] Quogosi (I_to_S)
[152/209] Rayoloth (S_to_I)
[153/209] Rotomouk (I_to_S)
[154/209] Sahuhe (S_to_I)
[155/209] Secochi (S_to_I)
[156/209] Sejile (I_to_S)
[157/209] Selebes (I_to_S)
[158/209] Sevoopir (I_to_S)
[159/209] Sipisa (S_to_I)
[160/209] Sithiroo (S_to_I)
[161/209] Slathalu (I_to_S)
[162/209] Slesuegig (I_to_S)
[163/209] Snonoque (S_to_I)
[164/209] Socrowa (S_to_I)
[165/209] Sopeyak (S_to_I)
[166/209] Soyefaf (S_to_I)
[167/209] Stragotom (I_to_S)
[168/209] Strousuhe (S_to_I)
[169/209] Sulokuf (I_to_S)
[170/209] Tadilsog (I_to_S)
[171/209] Talodut (S_to_I)
[172/209] Tatufok (I_to_S)
[173/209] Tecerouf (S_to_I)
[174/209] Thameci (I_to_S)
[175/209] Thisuga (I_to_S)
[176/209] Tieriegi (S_to_I)
[177/209] Tomamel (I_to_S)
[178/209] Tosbeybrof (I_to_S)
[179/209] Trecuquem (I_to_S)
[180/209] Tubafu (I_to_S)
[181/209] Tupotu (S_to_I)
[182/209] Udmodas (I_to_S)
[183/209] Udutek (S_to_I)
[184/209] Urpofooy (S_to_I)
[185/209] Ururtos (S_to_I)
[186/209] Uzegbex (I_to_S)
[187/209] Vokuba (S_to_I)
[188/209] Wetufru (S_to_I)
[189/209] Yobofre (I_to_S)
[190/209] Apuefquor (S_to_I)
[191/209] Befeto (S_to_I)
[192/209] Fecoostra (I_to_S)
[193/209] Fejoba (I_to_S)
[194/209] Gemapoey (S_to_I)
[195/209] Grefuci (I_to_S)
[196/209] Gristropu (I_to_S)
[197/209] Heruemey (S_to_I)
[198/209] Ibdarnif (S_to_I)
[199/209] Kacague (I_to_S)
[200/209] Kadiforn (S_to_I)
[201/209] Netstegup (S_to_I)
[202/209] Nufotoy (S_to_I)
[203/209] Quigliri (I_to_S)
[204/209] Senaniel (I_to_S)
[205/209] Somenut (I_to_S)
[206/209] Suedrurnep (I_to_S)
[207/209] Swibihek (I_to_S)
[208/209] Ugitat (S_to_I)
[209/209] Upbapit (S_to_I)

Done. Images saved to /home/ayeluru/vascular-superenhancement-4d-flow/notebooks/sandbox/velocity_direction_check_images